### ISSUE TITLE
Training cost

### ISSUE THREAD

**Issue by aopolin-lv** [intuitive-robots/mdt_policy#1]
Hello, authors! This is an excellent work.

What are the training costs on each dataset? What kind of gpu cards to use and how many hours to train?

**Comment by mbreuss** [comment]
Hi, the training on ABCD took around 10 hours on 4 A6000 GPUs and the training on D only takes around 6 hours. You can check the logs of the pretrained models for example times with evaluation included. Evaluation during training lasts about 30-60 minutes for all 1k rollouts with 4 GPUs.

**Comment by aopolin-lv** [comment]
> Hi, the training on ABCD took around 10 hours on 4 A6000 GPUs and the training on D only takes around 6 hours. You can check the logs of the pretrained models for example times with evaluation included. Evaluation during training lasts about 30-60 minutes for all 1k rollouts with 4 GPUs.

Thank you for your reply!
