### ISSUE TITLE
When to release the code about libero exp?

### ISSUE THREAD

**Issue by Nimolty** [intuitive-robots/mdt_policy#2]
Hello, fantastic works!
I was wondering whether there is a plan to release code about libreo experiments, thanks!

**Comment by mbreuss** [comment]
Hi, 
happy to hear you like it! Unfortunately, the libero code is still a big mess and i did not have time to clean it up as I am busy with other projects. So I decided to only release the clean CALVIN for now. if that changes, I will let you know.
