### ISSUE TITLE
learning curve

### ISSUE THREAD

**Issue by COST-97** [intuitive-robots/mdt_policy#4]
Hello:
    Excellent work!
     Could you share your learning curve in the Calvin task ABCD dataset?
    Thanks.

**Comment by mbreuss** [comment]
Hi,

below are the logged values for wandb for a run on abcd:


<img width="1110" alt="image" src="https://github.com/user-attachments/assets/5c21a527-8678-45ad-94f7-57f8fbb38bee">
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/89c74a1e-50e9-4b7b-86e8-1dd0bb546b42">
