### ISSUE TITLE
ImportError: Error loading module 'lfp.utils.transforms.NormalizeVector'

### ISSUE THREAD

**Issue by dingjiansw101** [intuitive-robots/mdt_policy#5]
Dear autors, thanks for sharing code of this great work. When I try to run the code, I met this error "ImportError: Error loading module 'lfp.utils.transforms.NormalizeVector'." How to solve this problem?

**Comment by omeryagmurlu** [comment]
Which script were you trying to run when you encountered this error?

**Comment by dingjiansw101** [comment]
Hi, this is the script that I try to run
`python mdt/training.py`

**Comment by omeryagmurlu** [comment]
I have tried installing the codebase in a new conda environment from scratch and wasn't able to reproduce your error. Can you try again using the instructions from here: https://github.com/intuitive-robots/mdt_policy?tab=readme-ov-file#installation

If you have problems installing pyhash: `conda install pyhash` worked for me
