### ISSUE TITLE
What does 'calvin_d_old/' mean?

### ISSUE THREAD

**Issue by ygtxr1997** [intuitive-robots/mdt_policy#7]
In your config_d.yaml, the root_data_dir is: `/home/hk-project-robolear/ft4740/code/calvin_d_old/dataset/task_D_D`. Does the 'calvin_d_old' word mean that it is an old version of CALVIN dataset? Or does it have other meanning?

**Comment by mbreuss** [comment]
Hi, thanks for the question. The data was just stored under an older project that I renamed to calvin_d_old. The name has nothing to do with another version of CALVIN itself, as there only exists the current one. 
Just download the dataset yourself and overwrite this variable.

**Comment by ygtxr1997** [comment]
Thank you for your quick response!
